version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5454:5432
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=speckle
      - POSTGRES_USER=speckle
      - POSTGRES_DB=speckle_main
