version: '3.9'

services:
  main-db:
    build:
      context: aiven_postgres
      dockerfile: Dockerfile
    volumes:
      - ./.data/main-db:/var/lib/postgresql/data
    ports:
      - 5454:5432
    environment:
      - POSTGRES_PASSWORD=speckle
      - POSTGRES_USER=speckle
      - POSTGRES_DB=speckle
    extra_hosts:
      - host.docker.internal:host-gateway

  region-1-db:
    build:
      context: aiven_postgres
      dockerfile: Dockerfile
    volumes:
      - ./.data/region-1-db:/var/lib/postgresql/data
    ports:
      - 5455:5432
    environment:
      - POSTGRES_PASSWORD=speckle
      - POSTGRES_USER=speckle
      - POSTGRES_DB=speckle
    depends_on:
      - main-db

    extra_hosts:
      - host.docker.internal:host-gateway

  region-2-db:
    build:
      context: aiven_postgres
      dockerfile: Dockerfile
    volumes:
      - ./.data/region-2-db:/var/lib/postgresql/data
    ports:
      - 5456:5432
    environment:
      - POSTGRES_PASSWORD=speckle
      - POSTGRES_USER=speckle
      - POSTGRES_DB=speckle
    depends_on:
      - main-db

    extra_hosts:
      - host.docker.internal:host-gateway
